#!/usr/bin/env bash

set -euo pipefail

log() {
  local level=$1
  shift
  printf '[%s] %s\n' "$level" "$*"
}

ensure_prerequisites() {
  log INFO 'apt パッケージの更新と必須ツール確認...'

  if [ ! -f /etc/os-release ]; then
    log ERROR 'Ubuntu / Debian 系ディストリビューションが必要です'
    exit 1
  fi

  sudo apt-get update -y
  sudo apt-get install -y curl ca-certificates gnupg
}

ensure_node_and_pnpm() {
  log INFO 'Node.js / pnpm を確認しています...'

  if ! command -v node >/dev/null 2>&1; then
    curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
    sudo apt-get install -y nodejs
  fi

  if ! command -v pnpm >/dev/null 2>&1; then
    corepack enable
    corepack prepare pnpm@latest --activate
  fi

  log INFO "Node.js $(node --version)"
  log INFO "pnpm $(pnpm --version)"
}

create_env_file() {
  log INFO 'Generating apps/api/.env.local...'

  cat > apps/api/.env.local <<'EOF'
# Generated by install-back-agent.sh

DATABASE_URL="postgresql://postgres:postgres@localhost:5432/podcast"
QDRANT_URL="http://localhost:6333"

PORT=3001
NODE_ENV=development
LOG_LEVEL=info

OPENAI_API_KEY="your-openai-api-key-here"
EOF

  log WARN 'OPENAI_API_KEY を apps/api/.env.local で設定してください'
}

install_dependencies() {
  log INFO 'Installing project dependencies via pnpm...'
  pnpm install
}

main() {
  log INFO '=== Podcast Search Back Agent install start ==='

  ensure_prerequisites
  ensure_node_and_pnpm
  create_env_file
  install_dependencies

  log INFO 'Install completed. 次のステップ:'
  log INFO '  1. Cursor Background Agent が setup/start を自動実行'
  log INFO '  2. 必要に応じて Docker は手動で用意してください'
}

main "$@"
